name: sscma

channels:
  - defaults
  - pytorch
  - nvidia

dependencies:
  - cudatoolkit==11.7   # mmcv pre-built wheels currently requires cuda 11.7
  - python>=3.8, <= 3.10
  - pytorch<=2.0.1
  - pytorch-cuda>=11.7  # mmcv pre-built wheels currently requires cuda 11.7
  - torchaudio<=2.0.2
  - torchvision<=0.15.2
  - pip>=23.0.1
  - pip:
    - -r requirements/base.txt
